name: TechChallenge3 Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
      
    - name: Restore dependencies
      run: dotnet restore TechChallengeFase1.sln --force
      
    - name: Build
      run: dotnet build TechChallengeFase1.sln --no-restore
      
    - name: Test
      run: dotnet test TechChallengeFase1.sln --no-build --no-restore --verbosity normal
